package com.github.sebastiankg02.csy2061as2.user;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 * User - data representation of a User within the application.
 * UserHelper - internal class within the user space that can directly manipulate User information from the SQLite DB
 **/
public class User {
	//Only allowed these chars in pasword (and their capitalised equivalents)
    public static final char[] passwordChars = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
    //Only allowed these numbers in password
	public static final char[] passwordNumbers = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
    //Minimum character length for passwords
	public static final int passwordMinChars = 8;

	//Internal user ID as generated by the database
    public int id;
	//User full name as set by user 
    public String fullName;
	//User email as set by user - this will be their login ID
    public String email;
	//Date&Time user registered for application
    public LocalDateTime registeredDate;
	//Date&Time user last updated their profile information 
    public LocalDateTime updatedDate;
	//User login oassword 
    public String password;
	//User hobbies - currently unused! TODO: Implement category sorting based on hobbies 
    public String hobbies;
	//User shipping & billing address
    public String address;
	//User access level - equivalent of 0 or 1, where 0 is standard access and 1 is admin access. 
    public UserAccessLevel level;

	//LocalDateTime formatter used application-wide
    public static DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

	//Default constructor, initalise object fields 
    public User(){
        this.id = 0;
        this.fullName = "NO NAME";
        this.email = "no@email.found";
        this.registeredDate = LocalDateTime.now();
        this.updatedDate = LocalDateTime.now();
        this.password = "password";
        this.hobbies = "";
        this.address = "SOMEWHERE AND NOWHERE";
        this.level = UserAccessLevel.USER;
    }

	//Full custom constructor when users are re-constructed fro the DB, assign fields
    public User(int id, String name, String email, String registered, String updated, String password, String hobbies, String address, int level){
        this.id = id;
        this.fullName = name;
        this.email = email;
        this.registeredDate = LocalDateTime.parse(registered, formatter);
        this.updatedDate = LocalDateTime.parse(updated, formatter);
        this.password = password;
        this.hobbies = hobbies;
        this.address = address;
        this.level = UserAccessLevel.getLevelFromInt(level);
    }

	//Simple constructor (no level or hobbies)
    public User(int id, String name, String email, LocalDateTime registered, LocalDateTime updated, String password, String address){
        this.id = id;
        this.fullName = name;
        this.email = email;
        this.registeredDate = registered;
        this.updatedDate = updated;
        this.password = password;
        this.hobbies = "";
        this.address = address;
        this.level = UserAccessLevel.getLevelFromInt(0);
    }

	/**
	 * SQLiteOpenHelper adaptation for the User data object - handles data object management via CRUD.
	 **/
    public static class DBHelper extends SQLiteOpenHelper {

		//Default constructor
        public DBHelper(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
            super(context, name, factory, version);
        }

		//Simplified constructor
		public DBHelper(@Nullable Context context){
			super(context, "KWD", null, 1);
		}
		
		//Table cretion method
        @Override
        public void onCreate(SQLiteDatabase sqLiteDatabase) {
            sqLiteDatabase.execSQL("" +
                    "CREATE TABLE user(" +
                    "ID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                    "NAME TEXT NOT NULL," +
                    "EMAIL TEXT NOT NULL," +
                    "REGISTERED TEXT NOT NULL," +
                    "UPDATED TEXT," +
                    "PASSWORD TEXT NOT NULL," +
                    "HOBBIES TEXT," +
                    "ADDRESS TEXT NOT NULL," +
                    "LEVEL INT NOT NULL)");
        }

		//Load data user object into db
        public boolean addUser(User u){
			//Overwrite & duplication protection
            for(User o: getUsers()){
                if(o.email.equals(u.email)){
                    return false;
                }
            }

			//Create data connection to db
            SQLiteDatabase data = this.getWritableDatabase();
            ContentValues output = new ContentValues();

            output.put("NAME", u.fullName);
            output.put("EMAIL", u.email);
            output.put("REGISTERED", formatter.format(u.registeredDate));

			//As updated date can be null, enforce rule
            if (u.updatedDate != null) {
                output.put("UPDATED", formatter.format(u.registeredDate));
            }

            output.put("PASSWORD", u.password);

			//As hobbies can be null, enforce rule
            if (u.hobbies != null) {
                output.put("HOBBIES", u.hobbies);
            }

            output.put("ADDRESS", u.address);
            output.put("LEVEL", u.level.value);
			
			//Insert object and close db connection
            data.insert("user", null, output);
            data.close();
            return true;
        }

		//Update existing user data
        public void updateUser(User newUser){
            SQLiteDatabase db = this.getWritableDatabase();
            ContentValues cv = new ContentValues();
            cv.put("NAME", newUser.fullName);
            cv.put("UPDATED", formatter.format(LocalDateTime.now()));
            cv.put("PASSWORD", newUser.password);
            cv.put("HOBBIES", newUser.hobbies);
            cv.put("ADDRESS", newUser.address);
            db.update("user", cv, "ID = ?", new String[]{String.valueOf(newUser.id)});
            db.close();
        }

		//Get all users currently registered in DB
        public ArrayList<User> getUsers(){
            ArrayList<User> output = new ArrayList<User>();
            SQLiteDatabase db = this.getReadableDatabase();
			//Loop through all entries in user db
            Cursor c = db.rawQuery("SELECT * FROM user", null);
            c.moveToFirst();
            while(!c.isAfterLast()){
                int id = c.getInt(c.getColumnIndexOrThrow("ID"));
                String name = c.getString(c.getColumnIndexOrThrow("NAME"));
                String email = c.getString(c.getColumnIndexOrThrow("EMAIL"));
                String registered = c.getString(c.getColumnIndexOrThrow("REGISTERED"));
                String updated = c.getString(c.getColumnIndexOrThrow("UPDATED"));
                String password = c.getString(c.getColumnIndexOrThrow("PASSWORD"));
                String hobbies = c.getString(c.getColumnIndexOrThrow("HOBBIES"));
                String address = c.getString(c.getColumnIndexOrThrow("ADDRESS"));
                int userLevel = c.getInt(c.getColumnIndexOrThrow("LEVEL"));

                User u = new User(id, name, email, registered, updated, password, hobbies, address, userLevel);
                output.add(u);
                c.moveToNext();
            }

            c.close();
            db.close();
            return output;
        }

        public User getSpecificUser(String email, String password){
            for(User u: getUsers()){
                if(u.email.equals(email) && u.password.equals(password)){
                    return u;
                }
            }
            return null;
        }

        public User getSpecificUser(int id){
            for(User u: getUsers()){
                if(u.id == id){
                    return u;
                }
            }
            return null;
        }

        public void deleteUser(String email){
            SQLiteDatabase db = this.getWritableDatabase();
            db.delete("user", "EMAIL = ?", new String[]{email});
            db.close();
        }

        @Override
        public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
            sqLiteDatabase.execSQL("DROP TABLE IF EXISTS user");
        }
    }
}
